"""
模板渲染模块

使用 Jinja2 将生成的章节草稿注入到用户指定的模板中
"""

import os
from pathlib import Path
from typing import Dict, Any
from jinja2 import Template, FileSystemLoader, Environment


def _generate_references_list(drafts: Dict[str, str]) -> str:
    import re
    all_citations = []
    seen = set()
    for content in drafts.values():
        cn_citations = re.findall(r'（[^）]+\d{4}）', content)
        en_citations = re.findall(r'\([^)]*?\d{4}\)', content)
        for c in cn_citations + en_citations:
            if c not in seen:
                seen.add(c)
                all_citations.append(c)
    all_citations.sort(key=lambda x: re.search(r'\d{4}', x).group() if re.search(r'\d{4}', x) else '0')
    return '\n'.join(all_citations)


def render_final_paper(template_path: str, drafts: Dict[str, str], output_dir: str = "output") -> str:
    """
    渲染最终论文
    
    Args:
        template_path: 模板文件路径
        drafts: 各章节草稿（章节名 -> 内容）
        output_dir: 输出目录
    
    Returns:
        输出文件路径
    """
    # 确保输出目录存在
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # 读取模板文件
    template_file = Path(template_path)
    if not template_file.exists():
        raise FileNotFoundError(f"模板文件不存在：{template_path}")
    
    with open(template_file, 'r', encoding='utf-8') as f:
        template_content = f.read()
    
    # 创建 Jinja2 模板
    template = Template(template_content)
    
    # 准备渲染上下文
    context = {
        'chapter_1': drafts.get('1 绪论', ''),
        'chapter_2': drafts.get('2 柑橘多视角图像采集与数据处理', ''),
        'chapter_3': drafts.get('3 基于多视角注意力融合的检测模型构建', ''),
        'chapter_4': drafts.get('4 实验结果与对比分析', ''),
        'chapter_5': drafts.get('5 柑橘实蝇智能检测与问答系统设计与实现', ''),
        'chapter_6': drafts.get('6 总结与展望', ''),
        'keywords': drafts.get('关键词', ''),
        'english_abstract': drafts.get('英文摘要', ''),
        'english_keywords': drafts.get('英文关键词', ''),
        'references': drafts.get('参考文献', ''),
        'acknowledgements': drafts.get('致谢', ''),
        'references_list': _generate_references_list(drafts),
        'drafts': drafts
    }
    
    # 渲染模板
    rendered_content = template.render(**context)
    
    # 确定输出文件名
    output_filename = f"paper{template_file.suffix}"
    output_file = output_path / output_filename
    
    # 保存渲染后的内容
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(rendered_content)
    
    print(f"论文已渲染并保存到：{output_file}")
    return str(output_file)


def create_default_template(template_type: str = "markdown", output_path: str = "data/templates") -> str:
    """
    创建默认模板
    
    Args:
        template_type: 模板类型（"markdown" 或 "latex"）
        output_path: 输出路径
    
    Returns:
        创建的模板文件路径
    """
    output_dir = Path(output_path)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    if template_type == "latex":
        template_content = r"""\documentclass[12pt]{article}
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{ctex}

\title{AutoPaperGen 生成的论文}
\author{AutoPaperGen 系统}
\date{\today}

\begin{document}

\maketitle

\begin{abstract}
{{ english_abstract }}
\end{abstract}

\section{绪论}
{{ chapter_1 }}

\section{柑橘多视角图像采集与数据处理}
{{ chapter_2 }}

\section{基于多视角注意力融合的检测模型构建}
{{ chapter_3 }}

\section{实验结果与对比分析}
{{ chapter_4 }}

\section{柑橘实蝇智能检测与问答系统设计与实现}
{{ chapter_5 }}

\section{总结与展望}
{{ chapter_6 }}

\end{document}
"""
        template_file = output_dir / "template.tex"
    else:  # markdown
        template_content = """# {{ title | default('AutoPaperGen 生成的论文') }}

## 关键词

{{ keywords }}

## 英文摘要

{{ english_abstract }}

## 英文关键词

{{ english_keywords }}

## 1 绪论

{{ chapter_1 }}

## 2 柑橘多视角图像采集与数据处理

{{ chapter_2 }}

## 3 基于多视角注意力融合的检测模型构建

{{ chapter_3 }}

## 4 实验结果与对比分析

{{ chapter_4 }}

## 5 柑橘实蝇智能检测与问答系统设计与实现

{{ chapter_5 }}

## 6 总结与展望

{{ chapter_6 }}

## 参考文献

{{ references }}

## 致谢

{{ acknowledgements }}

---
*Generated by AutoPaperGen*
"""
        template_file = output_dir / "template.md"
    
    with open(template_file, 'w', encoding='utf-8') as f:
        f.write(template_content)
    
    print(f"已创建默认模板：{template_file}")
    return str(template_file)
